### ISSUE TITLE
Support Python 2

### ISSUE THREAD

**Issue by kerrickstaley** [kerrickstaley/genanki#1]
Python 2 is never going to die. Support Python 2 for those poor unenlightened souls who can't or won't use Python 3.

**Comment by kerrickstaley** [comment]
(I'm not actively working on this and probably won't, this is more a tracking bug in case someone else wants to take this on).

**Comment by swayson** [comment]
Python 2 is on its way out. Don't think this is necessary. Pandas, numpy, matplotlib are all stopping support for Python 2 in a few months...

**Comment by kerrickstaley** [comment]
This will not happen, goodbye Python 2!
