### ISSUE TITLE
Subdecks

### ISSUE THREAD

**Issue by RomanADavis** [kerrickstaley/genanki#107]
Is there a way to generate decks as subdecks with genanki? If not, what would be required to add this functionality?

**Comment by RomanADavis** [comment]
Nevermind. It seems that you can do this by naming the decks `f"{deck}:{subdeck}"`, the only problem now is getting the subdecks in order.

**Comment by RomanADavis** [comment]
Apparently, Anki does not support this, but you can get around it by prepending your subdeck with a zero padded ordinal, i.e. `f"{subdeck}::{str(index + 1).zfill(2)} {deck}"`

**Comment by tyler-keller** [comment]
> Nevermind. It seems that you can do this by naming the decks `f"{deck}:{subdeck}"`, the only problem now is getting the subdecks in order.

Sorry, unsure if this is due to an update but I only achieved this functionality by using a :: like `f"{deck}::{subdeck}"`. Just leaving this here in case someone else comes across the same.
