### ISSUE TITLE
How to add cards to an existing deck

### ISSUE THREAD

**Issue by drudd75077** [kerrickstaley/genanki#115]
Following this instructions I can understand how to create a new deck, but how can I add a card to an existing deck? I don't want to lose the history of existing cards, but want to add new cards to learn on the same subject.

**Comment by kerrickstaley** [comment]
Importing a .apkg file is not supported. You can however generate a new .apkg file, import it into Anki, and then using the "Browse" UI select the new cards and choose "Change Deck" to move them into your existing deck.

**Comment by jjjchens235** [comment]
I was also trying to find this information, maybe it would be worth it to make a small note of this in the readme.
