### ISSUE TITLE
Apkg cannot be importet to Anki Desktop: JsonError { info: "decoding modesl: JsonError" }

### ISSUE THREAD

**Issue by robert-elles** [kerrickstaley/genanki#120]
**Description**
I used genanki to generate a simple card deck. I can open it with AnkiDroid but in the desktop version of Anki it reports the following error: JsonError { info: "decoding modesl: JsonError" }

Also the deck cannot be synced to anki web from ankidroid

**To reproduce**
See the attached file. Just rename file ending zip to apkg

**Expected behavior**
Opens normally

**Actual behavior**
Anki desktop shows the following error message:  JsonError { info: "decoding modesl: JsonError" } 

**genanki version**
0.13.0
[mydeck.zip](https://github.com/kerrickstaley/genanki/files/11787783/mydeck.zip)

**Additional context**
Anki Desktop version is: 2.1.61

**Comment by robert-elles** [comment]
I found the cause of this error. The name field of my template was missing.

**Comment by Ljupch0** [comment]
I had a similar error and the issue was non-numeric characters in the model id.
