### ISSUE TITLE
Please provide examples and explanations for creating custom models 

### ISSUE THREAD

**Issue by HendrikHuebner** [kerrickstaley/genanki#126]
I would like to learn more about how I can apply custom styling to my cards with html and css. The documentation is very short.

**Comment by kerrickstaley** [comment]
Anki's docs have lots of information about how to use HTML and CSS to style cards: https://docs.ankiweb.net/templates/styling.html

**Comment by raine** [comment]
>  Anki's docs have lots of information about how to use HTML and CSS to style cards: https://docs.ankiweb.net/templates/styling.html

There is no documentation on how to add styles with `genanki` specifically. Which is a fair point.

To anyone else wondering, you need to use the `css` parameter in Model's constructor.
