### ISSUE TITLE
Is it possible to change 'Editing font'?

### ISSUE THREAD

**Issue by JaeyongMed** [kerrickstaley/genanki#129]
![CleanShot 2024-02-05 at 15 07 02@2x](https://github.com/kerrickstaley/genanki/assets/117558394/c78f4eff-afb5-4d97-a60e-2fb53a259f0e)

**Expected behavior**
Is there an option to specify editing font and size?

**Comment by kerrickstaley** [comment]
You can do this by setting the `'font'` key in the dict for that field when creating the `Model`. For example:
```
fields=[
  {'name': 'Question'},
  {'name': 'Answer', 'font': 'Arial Black'},
],
```
