### ISSUE TITLE
how to create multi-level directory by using genanki 

### ISSUE THREAD

**Issue by YuseiwithJackandCrow** [kerrickstaley/genanki#136]
I have extracted many words from a book and I want to create a single deck file, but with expandable subdirectories where the subdirectory names serve as the titles.
there is an example
![二级目录](https://github.com/kerrickstaley/genanki/assets/55986612/ecfcee0e-3522-476c-ae14-7c871e179c79)

**Comment by tyler-keller** [comment]
Hey, was looking for a similar solution and found it here:
https://github.com/kerrickstaley/genanki/issues/107

**Comment by tyler-keller** [comment]
Found the answer here:
https://github.com/kerrickstaley/genanki/issues/107

You can name a deck `f'{deck_name}::{subdeck_name}')` to get a similar drop down functionality.

**Comment by YuseiwithJackandCrow** [comment]
> Found the answer here: #107
> 
> You can name a deck `name=f'{deck_name}::{subdeck_name}'` to get a similar drop down functionality.

thank you so much.I have just see your reply right now. your methods are indeed helpful.
