### ISSUE TITLE
Default Models

### ISSUE THREAD

**Issue by kerrickstaley** [kerrickstaley/genanki#2]
Creating Models is hard, let's add some default models based on Anki's built-in ones.

**Comment by fny** [comment]
You have any tips on how to go about doing that? I've tried to create one based on the existing ID, but your model class requires all the attributes (i.e. template) to be specified too.

**Comment by StefanGreve** [comment]
@fny What we could do is writing sample models for the community. Alternatively, search for repositories on GitHub that list this dependency. I used [this guide](https://charly-lersteau.com/post/2019-11-17-create-anki-deck-csv/) as a starting point a recent project. Replace the template with a template you already use in a pre-existing Anki deck. You can find this information in the Anki app in `Browse`. Select any deck, click on `Cards` and copy the CSS & Front/Back Template. It's really easy once you got that figured out.

**Comment by mentheosis** [comment]
I wrote something that may be useful to you guys, its a tool that reads the user's existing anki models and allows the user to choose one of those to set as the model for importing with genanki: https://github.com/mentheosis/anki-scanner-chinese-redux/blob/master/chinese/mr_note_maker.py#L70

**Comment by kerrickstaley** [comment]
Fixed in ec5847e0faea8de225aa079d101b85f7e08652a6
