### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by jedet** [kerrickstaley/genanki#24]
Hi Kerrick,

I have found this repository and very much like it. Thank your for investing your time into that code.
As I have not too much experience with python and some with Linux, I struggle to get it to run.

I have managed to download and install these 3 packages:
-    cached-property
-    frozendict
-    pystache

but "pyyaml" I am not sure if it was installed, as I downloaded that manually and not with the Software Manager of Linux.
When I do a "make install" in the "genanki-master"-directory, I receive this output:

```
python3 setup.py install --user
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'
Makefile:3: recipe for target 'install' failed
make: *** [install] Error 1

```
It seems like it point to this line here: https://github.com/kerrickstaley/genanki/blob/6d173fcd8a50b29164d733fce750276bc9a9f39d/setup.py#L1
I have not been able to find that directory or file "setuptools". Where is that?

Thank you very much for your help :)

Best regards
Joel

**Comment by Kentoseth** [comment]
Try installing everything using a Virtual Environment.

Are you on Linux?

Doing so on Linux can be found here:

https://help.dreamhost.com/hc/en-us/articles/115000695551-Installing-and-using-Python-s-virtualenv-using-Python-3

After creating your virtualenv environment, you simply do:

`pip install genanki`

**Comment by jedet** [comment]
Dear Kerrick

Thank you.

Nowadays I have already switched to the csv-file-approach, because that is anyway easier

Thank you for your answer
Many Blessings
Joel
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
