### ISSUE TITLE
Add media / sound support

### ISSUE THREAD

**Issue by cykl** [kerrickstaley/genanki#4]
I had like to use genanki to create cards having a sound as front side. 

My understanding is that it is not yet possible because genanki does not support media. Do you plan to add media support?

**Comment by kerrickstaley** [comment]
otkoge is working on this in https://github.com/kerrickstaley/genanki/pull/6, should be merged soon.

**Comment by cykl** [comment]
Thanks for telling me. I will give it a try when merged (I wrote similar code to patch the Zip so I am not blocked).

**Comment by kerrickstaley** [comment]
Media files are now supported as of version 0.3.0, which is published on PyPI. See the docs here: https://github.com/kerrickstaley/genanki#media-files
