### ISSUE TITLE
Seeking clarification as to which is the 'real' master branch

### ISSUE THREAD

**Issue by JoanEliot** [kerrickstaley/genanki#41]
I'm confused as to the connection between this branch and the one here:
https://github.com/dvklopfenstein/genanki

Though the dvklopfenstein fork has the same version number it appears to have received more recent contributions from kerrickstaley than this branch has. For that reason, I'm using the dvklopfenstein fork. 

Should I be? And if I have questions to ask or issues to report, where should I post them? I guess here because the other fork's "Issues" button is missing, but please confirm.

**Comment by kerrickstaley** [comment]
Please report bugs against this repository.

dvklopfenstein's fork was created for this PR: https://github.com/kerrickstaley/genanki/pull/37

**Comment by JoanEliot** [comment]
Belated appreciations for the response.
