### ISSUE TITLE
Add GitHub Topic: anki-flashcards or similar

### ISSUE THREAD

**Issue by katrinleinweber** [kerrickstaley/genanki#47]
Thanks for publishing this! In case you'd like to make [your repo more findable](https://github.com/topics/anki-flashcards), you could [add that topic](https://help.github.com/articles/about-topics/), or another common topic that those other projects use ;-) Thank you!

**Comment by kerrickstaley** [comment]
Done! Thanks for the suggestion :)

**Comment by katrinleinweber** [comment]
Thank you :-)
