### ISSUE TITLE
How can I apply cloze?

### ISSUE THREAD

**Issue by gelodefaultbrain** [kerrickstaley/genanki#57]
Hello! Thank you for this library :) really been helpful! 

May I ask on how can I apply cloze. I am trying to read this data from google doc but when I generate a deck, it doesn't work

![image](https://user-images.githubusercontent.com/55988471/96545174-76c93380-12da-11eb-8cee-91cb94afea26.png)

Instead I get this 

![image](https://user-images.githubusercontent.com/55988471/96545189-7e88d800-12da-11eb-9cec-96344cc28ba2.png)

Here is the code where I generate the deck. Thank you

```
model = genanki.Model(1607392319,'USC1 Sample Model',
		fields=[
			{'name': 'Question'},
			{'name': 'Answer'}
		],
		templates=[
			{
				'name': 'Card 1',
				'qfmt': '{{Question}}',
				'afmt': '{{FrontSide}}<hr id="answer">{{Answer}}',
			},

		])


	deck = genanki.Deck(2059400110,'USC1 Beta Deck')

	for key,value in output_dict.items():
		if isinstance(value,Mapping) == True:
			for subkey,subvalue in value.items():
				answer = subkey
				if subvalue:
					answer = f"{subkey} <ul>"+ ''.join([f"<li>{sa}</li>" for sa in subvalue]) + "<ul>"


				note = genanki.Note(
					model=model,
					fields=[key,answer])


				deck.add_note(note)
```

**Comment by kerrickstaley** [comment]
There is an example of how to use Cloze models [in the unit tests here](https://github.com/kerrickstaley/genanki/blob/7ac1ec8ca494d593f16bda3ee5fe1f44dd0f9203/tests/test_cloze.py#L61)
