### ISSUE TITLE
issue - multiline cloze detection (with solution)

### ISSUE THREAD

**Issue by mat383** [kerrickstaley/genanki#58]
### Issue:
Multiline cloze deletions aren't detected. When exporting deck to Anki, cards with multiline clozes (probably only the ones with multiline clozes, but I didn't test that) don't show. Only when database check is preformed they are detected and put into deck named "Default".

### Solution:
**~~Edit3: I tested my solution and seems that there is also some other problem~~**
Edit4: it seems to be working (I forgot to change model to cloze in my test)
Change in line 101 of file genanki/note.py:
```python
      card_ords.update(int(m)-1 for m in re.findall(r"{{c(\d+)::.+?}}", field_value) if int(m) > 0)
```
to:
```python
      card_ords.update(int(m)-1 for m in re.findall(r"{{c(\d+)::.+?}}", field_value, re.DOTALL) if int(m) > 0)
```
or:
```python
      card_ords.update(int(m)-1 for m in re.findall(r"{{c(\d+)::[\s\S]+?}}", field_value) if int(m) > 0)
```

### Explanation:
```.``` matches anything except a newline character ([relevant python3 doc](https://docs.python.org/3/howto/regex.html#matching-characters)).

### Example:
```python
test_str_part = \
"""
{{c1:: test 
}}
"""
clozes = re.findall(r"{{c(\d+)::.+?}}", test_str_part)
for e in clozes:
    print(e)
#cloze isn't detected
```

### Other:
I'm new to git and currently I don't have much time, but if I find any I will try to send commit with fixed code (if that's possible).

With regards
mat383

Edit1: expanded issue description
Edit2: grammar

**Comment by kerrickstaley** [comment]
This should be fixed in genanki 0.9.1; let me know if it works for you!
