### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by ryqiem** [kerrickstaley/genanki#69]
Hi guys! 

You're doing great work, and this software has allowed me to do a bunch of things I couldn't do without it. Is there a place I can donate to, or do you have a preferred charity? :-)

Martin

**Comment by kerrickstaley** [comment]
Thanks for the inquiry, I'm really flattered :)

I work a day job and don't have a need for donations, but I'd encourage you to donate to one of my favorite charities (listed below) or any cause you think is worthy.

- [GiveWell](https://www.givewell.org/)
- [The GNOME Foundation](https://www.gnome.org/support-gnome/)
- [The Electronic Frontier Foundation](https://www.eff.org/)
- [The Python Software Foundation](https://www.python.org/psf/donations/)
