### ISSUE TITLE
sort_field_index not released & what is sort_field doing?

### ISSUE THREAD

**Issue by filipre** [kerrickstaley/genanki#79]
Hi, 

I wanted to use `sort_field_index` but it appears the feature has not been released yet. The latest release is from December 2020 but `sort_field_index` was implemented only 3 months ago. Can you release a new version or is there another (clean) way to make use of that feature?

Also, to me it is not clear what `sort_field` is expecting. Is it
- n-th field to sort on, e.g. 1 for first field, 2 for second field
- value to be sorted on, e.g. a card with `sort_field=10` appears before a card with `sort_field=11`
- the name of the field to be sorted on, e.g. when there is a field called `Level`, then `sort_field="Level"` will sort all cards according to the value of the Field `Level`
- something else??

Thanks!

Best
René

**Comment by kerrickstaley** [comment]
`sort_field_index` is an integer which is the index of the field to sort on. 0 is the first field, 1 is the second, etc. You pass `sort_field_index` when constructing the `Model`.

You can also pass `sort_field` when constructing the `Note`. This is a string giving the actual contents of the sort field.

I've released [genanki 0.11.0](https://pypi.org/project/genanki/0.11.0/) which has the latest changes.

**Comment by filipre** [comment]
Thanks for the release and the clarification!
