### ISSUE TITLE
Add decription what does my_package.media_files = ['sound.mp3', 'images/image.jpg']

### ISSUE THREAD

**Issue by spider-x** [kerrickstaley/genanki#92]
Hello, it would be great to explain in manual what does my_package.media_files = ['sound.mp3', 'images/image.jpg']

**Comment by SumZbrod** [comment]
> Hello, it would be great to explain in manual what does my_package.media_files = ['sound.mp3', 'images/image.jpg']

the package is like a deck, but with media files:
my_package = genanki.Package(my_deck) 
my_package.media_files = audio_list # some list like ['sound.mp3', 'images/image.jpg']
my_package.write_to_file('deck_name.apkg')
P.S.: I spent 1 day figuring this out, hopefully it helps someone like me. And I hope it gets inserted into the documentation.

**Comment by chambln** [comment]
This seems to be documented quite thoroughly in the readme, so I think this can be closed now.

https://github.com/kerrickstaley/genanki/blob/336b666/README.md?plain=1#L80-L104

**Comment by kerrickstaley** [comment]
Agree with what chambln wrote; I think this is pretty well covered in the README. I intend to get a more detailed docs site up but don't have time right now.
