### ISSUE TITLE
if it possible to append to an existing apkg file?

### ISSUE THREAD

**Issue by sudeepdino008** [kerrickstaley/genanki#94]
Well, foremost, this is an amazing tool! Thanks a ton for this. 

Regarding my query, the title says it. I basically want to convert my kindle highlights into anki cards. I'll create and import the first apkg file. From next time on, I want cards to be created only for new highlights, and for that to be imported into anki. 

I don't want to create a new deck altogether and import that because that'd mess up with the repetition algorithm etc. and would be like starting from scratch.

**Comment by kerrickstaley** [comment]
Unfortunately, reading existing .apkg files isn't currently supported and isn't within the scope of the goals of this project.

**Comment by l-bowman** [comment]
> Unfortunately, reading existing .apkg files isn't currently supported and isn't within the scope of the goals of this project.

I'd like to second that being able to append and edit an existing deck would be amazing. If the subject matter for a deck evolves, as it often does, it would be great to capture this without starting from square one. Thanks for making a cool tool!
