### ISSUE TITLE
Media files are not being extracted

### ISSUE THREAD

**Issue by redsigma** [kerrickstaley/genanki#95]
I am not sure if i am doing something wrong but if i use the `package.media_files` as shown in the description, the resulted apkg archive contains all necessary files inside and they have correct values.

However i have checked `%appdata%\Anki2\<profile_name>\collection.media` and this folder remains empty after i install the apkg file.

If i manually drag all my media files there, then everything works as expected.

**Comment by konhi** [comment]
Did you manage to resolve your issue? I encountered the exact problem, however it seems using relative path is the current workaround for this.

✔ `data/audio.mp3` -> `audio.mp3`

**Comment by redsigma** [comment]
No i couldn't fix the problem. Currently i am manually copying the images and audio files to the `collection.media` folder. (for example  `collection.media/data_deck1/<files>`)  and i am adding them by the relative path which seems to point to the `collection.media` folder.

So the answer is that `package.media_files` either does nothing or does not work

**Comment by konhi** [comment]
Thanks for letting me know. I did a little testing. I created 2 packages:
1. with absolute paths
2. with relative paths

After some research, it turns out that both packages do contain media files. The only difference is in database file.

![image](https://user-images.githubusercontent.com/61631665/147578281-d546aca8-7a57-49a0-9cf6-b255a7e6b617.png)

Unfortunately, I'm not sure how to solve this issue. Perhaps someone more experienced could take a loot at it!
Meanwhile, if anybody needs to have a workaround - just temporarily move files from absolute path to current working directory.

**Comment by kerrickstaley** [comment]
@redsigma your bug report doesn't have enough info to debug what's happening. Please carefully read the instructions for adding media in the README, and if you are still having issues, try starting from the example in the README, get that working, and then incrementally change your code to do what you want. Also double-check that you're using the latest genanki version. If you discover bugs or usability issues with how media files are handled, please report them here :) When you post an issue, please include the exact code that you ran, what you expected it to do, and what it actually did.

@konhi I'm not sure what these relative.sql and absolute.sql files are. I just double-checked the behavior of `media_files` for both files in the current directory and files where you provide a relative or absolute path, and it works like expected in all cases. I might not be using it the same way as you. Can you post some Python code that does something different than you expect (ideally in a new bug report)?

**Comment by konhi** [comment]
@kerrickstaley Sorry for the inconvenience. Everything seems to be working as expected! 😅
Mistake I made was ignoring this:
> You should only put the filename (aka basename) and not the full path in the field; `<img src="images/image.jpg">` will not work. Media files should have unique filenames.

❌ So I did that:
```py
note = genanki.Note(MODEL, fields=['das', 'ten', f'[sound:data/pronunciation/de/das.mp3]'])
```

✔ Which should be:
```py
note = genanki.Note(MODEL, fields=['das', 'ten', f'[sound:das.mp3]'])
```

That how it would look finally:
```py
import genanki

# Basic Model with media file
MODEL = genanki.Model(
  1607392318,
  'Frekwencja Basic Model',
  fields=[
    {'name': 'Question'},
    {'name': 'Answer'},
    {'name': 'Pronunciation'}
  ],
  templates=[
    {
      'name': 'Card 1',
      'qfmt': '{{Question}} {{Pronunciation}}',
      'afmt': '{{Answer}}',
    },
  ])

deck = genanki.Deck(2059400112, 'Working Case') 
note = genanki.Note(MODEL, fields=['das', 'ten', f'[sound:das.mp3]'])
deck.add_note(note)

package = genanki.Package(deck, ['data/pronunciation/de/das.mp3'])
package.write_to_file('file.apkg')
```

Notice that **in media files, there should be full path.**

---
Perhaps we should add an example to readme?

**Comment by redsigma** [comment]
@konhi I ran the code above as well and it seems that it is working and the `.mp3` file  gets copied to `%appdata%Anki2\<profile>\collection.media\` 

The mistake which i was doing with using images was this:
```py
note = genanki.Note(MODEL, fields=['das', 'ten', 'test_meh.jpg'])  # test_meh.jpg won't be extracted
deck.add_note(note)
package = genanki.Package(deck, ['data/images/test_meh.jpg'])
```
The correct syntax is:
```py
note = genanki.Note(MODEL, fields=['das', 'ten', '<img src=test_meh.jpg>'])  # test_meh.jpg gets extracted correctly
deck.add_note(note)
package = genanki.Package(deck, ['data/images/test_meh.jpg'])
```
I was under the impression that i could add the  `<img src>` text inside the model and only mention the name of the files in the genanki.Note.

**Comment by kerrickstaley** [comment]
@redsigma doing `<img src="./{{Answer}}">` is not supported by Anki, as mentioned in the genanki README:

> You *cannot* put `<img src="{MyMedia}">` in the template and `image.jpg` in the field. See these sections in the Anki manual for more information: [Importing Media](https://docs.ankiweb.net/#/importing?id=importing-media) and [Media & LaTeX](https://docs.ankiweb.net/#/templates/fields?id=media-amp-latex).
> 
> You should only put the filename (aka basename) and not the full path in the field; `<img src="images/image.jpg">` will *not* work. Media files should have unique filenames.
